package com.example.blog_app.mapper;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.example.blog_app.dto.CommentRequest;
import com.example.blog_app.models.Comment;
import com.example.blog_app.models.Post;
import com.example.blog_app.models.UserObject;

@Mapper(componentModel = "spring")
public interface CommentMapper {

    /**
     * CommentRequest --> Comment
     * the id is ignored since it will be autogenerated by the database
     * @param commentRequest
     * @param post
     * @param user
     * @return
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "text", source = "commentRequest.text")
    @Mapping(target = "post", source = "post")
    @Mapping(target = "createdDate", expression = "java(java.time.Instant.now())")
    @Mapping(target = "user", source = "user")
    Comment map(CommentRequest commentRequest, Post post, UserObject user);


    /**
     * Comment --> CommentRequest
     * Map Comment to CommentRequest
     * @param comment
     * @return
     */
    @Mapping(target = "postId", expression = "java(comment.getPost().getPostId())")
    @Mapping(target = "username", expression = "java(comment.getUser().getUsername())")
    CommentRequest commentToDto(Comment comment);
}
